### ISSUE TITLE
Logged In, but no visits displayed

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#10]
Logged in as Ben Ball on Sat, 11/18/2018.  No visits displayed (date was displayed and blue background).  

Waited.  Still no visits.

Jiggled the handle (hit PREV and then NEXT).  Saturday visits appeared.

**Comment by teddyhoo** [comment]
Does this happen all the time. This sounds like a time-out type of issue. Can you run with the Android Studio IDE and view the Logcat output to see what is happening? And did you mean you logged in on 8/18/2018? Where did you get the 11 from? Is the date on your phone set correctly because that could impact things.

**Comment by teddyhoo** [comment]
Mattew

This app version has a different name identifier and will not overwrite the previous version. I wonder if you are tapping the wrong version when coming forward. I know that there are two places that a single app icon can show up — like a master app list and then a copy to the screen view. Frankly, I am not sure what the rationale is for that and I find it to be unnecessarily confusing. When you come back into the login view, check the version stamp at the bottom. 

When I routinely minimize the app, I relaunch it by tapping the icon not choosing from the background chooser.

If the above is not the issue, then run it through the Studio IDE and lets see what the output is. Same with the problem where you login and get just a blue screen. Those seem very much like timeouts. 

I’m going to upload a version that should fix the tap to arrive and complete. 

I found a couple of other crash triggers. 

Ted

**Comment by teddyhoo** [comment]
I got a blank blue screen when the app and or network was apparently really slow. It is a time out. If this happens again, the workaround is to cycle to background and bring to foreground.

**Comment by mattleashtime** [comment]
Thanks for the workaround.  Do you plan to fix this issue before we release the app?

**Comment by mattleashtime** [comment]
BTW, I uninstalled the LT app, downloaded the file linked to in your 8/15 email, and tried to replicate the start app>push to background>tap screen icon to return>get login screen issue.  I could not reproduce it, whether or not I started from a future day.

**Comment by mattleashtime** [comment]
Sorry my answers are scattered.  I have not observed the blank screen problem since the first report.  And yes, I mistyped the date.  8/18/2018 is correct.

**Comment by teddyhoo** [comment]
I am not sure if I should fix it at this juncture. Of course, it should be fixed, if you catch an exception after a timeout it should try again. But then the question becomes how many times should it try again -- not indefinitely, as there may be a legitimate reason for the time out and you are force cycling the app to keep doing the same thing over and over again expecting a different outcome. There are checks in place to make sure (1) a network connection exists (2) if so, and it if it is a captive wi-fi that the user's connex has been validated. The workaround is to cycle it back / fore again and again. Let's say they do that three times. The outcome if we kept catching and retrying exception would be the same. The cycle up and cycle background are perilous with multiple threads and numerous null checks as a result. In other words, to better handle this is no trivial matter.

**Comment by teddyhoo** [comment]
I'm going to mark this fixed. I wouldn't consider it broken, it could just perform better in the scenario where there is a timeout scenario.
