### ISSUE TITLE
"Show Client" flakiness

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#14]
LEASHTIME_2_0_AUGUST_24_2018.apk

Un-checking "Show Client" immediately erases client names.  Re-checking it does not restore them.  Cycling background/foreground restores SOME of them, but not all.  Specifically: bball1 on  8/24/2018.  Lily(Carly Carolina) owner does not return without logging out completely and returning.

**Comment by teddyhoo** [comment]
Was not updating all conditions of show no show client and setting field to visible / invisible.

**Comment by mattleashtime** [comment]
Confirmed fixed in LEASHTIME_2_0_AUGUST_27_2018.apk.
