### ISSUE TITLE
Excess GPS points from previous days

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/Android-Sitter-Mobile#16]
TonkaTEST
 I pulled the app forward today on my phone and it had still retained the points from that prior visit. I had not marked a visit complete on Friday. So as you can see the visit I marked arrived today has recorded coordinates from the last 2 days. This may be a problem for Multi- arrival walks.

![image](https://user-images.githubusercontent.com/41838025/44630939-c72aed80-a92a-11e8-9139-d8bd2b1b27eb.png)

![image](https://user-images.githubusercontent.com/41838025/44630943-cf832880-a92a-11e8-8044-14589df2656d.png)

**Comment by jodsmithLT** [comment]
Note for TonkaTEST - I DO NOT allow for concurrent visits under the Native app settings.

**Comment by teddyhoo** [comment]
Were these different clients? So on day of the normal gps activity you did not complete visit. Then the next day or two day, you marked arrive for a different visit but was it the same client? That is an interesting situation. How realistic would it be they would not close and not notice? And if so, should we really enforce multi-arrive policy if it is NO. Then of course there might need to be exception for overnights.
