### ISSUE TITLE
CRASH after NEXT, tap on visit

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#18]
LEASHTIME_2_0_AUGUST_27_2018.apk

Login.  
Wait a decent interval (10+ seconds).
Choose NEXT or PREV once or more.
Tap a visit.

App stops.

**Comment by teddyhoo** [comment]
I had a stray method call in there and if the value was null it was going to crash. I removed it and it is all good.
