### ISSUE TITLE
Version 2: Back icon function is confusing.

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#21]
Android 2.0. Back icon effectively ends session.

1.     Login.
2.     Hit "Back" icon.  App disappears.
3.     Tap app icon.  Login page appears.
4.     Hit "Back" icon.  Empty list for today.
5.     Hit "Back" icon.  App disappears.

Summary: "Back" from the main screen is a de facto logout.  "Back" from the main screen is simply confusing.

**Comment by teddyhoo** [comment]
This has been disabled (back button from MainActivity). It is also related to other ticket items.
