### ISSUE TITLE
Flag Doubling and unexpected session endings

### ISSUE THREAD

**Issue by mattleashtime** [teddyhoo/Android-Sitter-Mobile#23]
I found that the flag doubling I reported today is directly related to Issue 21 (Version 2: Back icon function is confusing.).

Try this:
1. Login as bball1/bball1 and wait till you see your visits.
2. View Bilbo Baggins Wizard or Xavier Ducey details.  Note that each flag shows just once.
3. Return to the visits view.
4. Hit the "back" icon/widget at the screen bottom.
5. Use the screen icon to return to LeashTime.
6. You are logged out.  Log in again.
7. View Bilbo Baggins Wizard or Xavier Ducey details.  Note that each flag shows TWICE.
8. Repeat Steps 3 - 7.  Note that each flag shows THREE times.
9. Repeat Steps 3 - 7.  Note that each flag shows FOUR times.
etc.

This scenario may seem unlikely, but it suggests that whatever is happening when the back key is used from the visit list, it is not completely cleaning up after itself.  There may even be orphan processes/listeners/whatever still working in parallel with the replacements which are generated when the session is restarted.

.

**Comment by teddyhoo** [comment]
I believe the issue with the back button resolved this issue.
