### ISSUE TITLE
Profile data -  City, State.  

### ISSUE THREAD

**Issue by jodsmithLT** [teddyhoo/Android-Sitter-Mobile#5]
This field on the APK file August 2nd is pulling up the Vets name Instead of Vet location.

TonkaTEST : Sitter Android : Client Rick Castle

![image](https://user-images.githubusercontent.com/41838025/44152158-65225506-a06a-11e8-85d8-0717663f2fda.png)

**Comment by teddyhoo** [comment]
A very simple typing error. It is fixed.
